### ISSUE TITLE
Erro no Site ao tentar prosseguir com as aulas

### ISSUE THREAD

**Issue by lasique** [gustavoguanabara/javascript#47]
Tentei acessar agora no período da tarde e foi normal, favor desconsiderar esse issue...

Olá professor Guanabara, primeiramente quero agradecer por disponibilizar seus conhecimentos com enorme maestria, tenho aprendido muito com suas aulas de forma muito fácil.
Hoje ao finalizar o vídeo da aula 11 do curso de Javascript do cursoemvideo, me deparei com o erro em anexo, poderia me ajudar por gentileza? E ao tentar fazer logout para logar novamente para ver se eu conseguia ver o vídeo 12, apareceu esse erro:

Fatal error: Uncaught Error: Call to a member function get() on null in /home/cursoemvideo3/www/wp-content/plugins/cev-addons-for-woocommerce/modules/custom-bar/includes/class-cevaw-custom_bar.php:217 Stack trace: #0 /home/cursoemvideo3/www/wp-content/plugins/cev-addons-for-woocommerce/modules/custom-bar/includes/class-cevaw-custom_bar.php(261): CEVAW_Custom_Bar->get_coupon_code() #1 /home/cursoemvideo3/www/wp-content/plugins/cev-addons-for-woocommerce/modules/custom-bar/includes/class-cevaw-custom_bar.php(298): CEVAW_Custom_Bar->show_bar() #2 /home/cursoemvideo3/www/wp-includes/class-wp-hook.php(307): CEVAW_Custom_Bar->render_content() #3 /home/cursoemvideo3/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #4 /home/cursoemvideo3/www/wp-includes/plugin.php(476): WP_Hook->do_action() #5 /home/cursoemvideo3/www/wp-includes/script-loader.php(2156): do_action() #6 /home/cursoemvideo3/www/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts() #7 /home/cursoemvideo3/www/wp-includes/class-wp-hook.php(331): WP_H in /home/cursoemvideo3/www/wp-content/plugins/cev-addons-for-woocommerce/modules/custom-bar/includes/class-cevaw-custom_bar.php on line 217
Há um erro crítico no seu site. Verifique seu e-mail para instruções.

[Saiba mais sobre a como resolver problemas do WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

Desde já meu muito obrigado!
![erro-site](https://user-images.githubusercontent.com/105525992/171618946-cfd6b010-b01d-46e4-9ea7-87ab8ed7d6d9.jpg)

**Comment by flameastro** [comment]
Olá, @lasique! Poderia fechar a issue?
